# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aefdb32d8f725d9675ac79b82ca268e282c7cef4a58705d0032fc5a99b7b3d7f69b9a6951ce6b43495c10fc95eda6c2dddfa19853ab3ff5296be914a4215d3b5

test:
  secret_key_base: bc9b3a97d7a05276ba87fb65cc80bd34115330498132662050644010c750e13aa9afb04b875227f01504c341d5cfa36714559d5b9b0b4b7495747f3f6413a3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
